my-- MySQL Script generated by MySQL Workbench
-- Tue Mar 29 23:27:52 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `userID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `firstName` VARCHAR(45) NOT NULL COMMENT '',
  `lastName` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `hashedPasswords` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`userID`)  COMMENT '',
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `accountID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `User_userID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`accountID`, `User_userID`)  COMMENT '',
  UNIQUE INDEX `accountID_UNIQUE` (`accountID` ASC)  COMMENT '',
  INDEX `fk_Account_User_idx` (`User_userID` ASC)  COMMENT '',
  CONSTRAINT `fk_Account_User`
    FOREIGN KEY (`User_userID`)
    REFERENCES `mydb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `transactionID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `userID` DATE NOT NULL COMMENT '',
  `category` VARCHAR(45) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `principal` VARCHAR(45) NOT NULL COMMENT '',
  `Account_accountID` INT UNSIGNED NOT NULL COMMENT '',
  `Account_User_userID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`transactionID`, `Account_accountID`, `Account_User_userID`)  COMMENT '',
  UNIQUE INDEX `transactionID_UNIQUE` (`transactionID` ASC)  COMMENT '',
  INDEX `fk_Transaction_Account1_idx` (`Account_accountID` ASC, `Account_User_userID` ASC)  COMMENT '',
  CONSTRAINT `fk_Transaction_Account1`
    FOREIGN KEY (`Account_accountID` , `Account_User_userID`)
    REFERENCES `mydb`.`Account` (`accountID` , `User_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
