-- MySQL Script generated by MySQL Workbench
-- Tue Apr 26 16:24:26 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 310Database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `310Database` ;

-- -----------------------------------------------------
-- Schema 310Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `310Database` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `310Database` ;

-- -----------------------------------------------------
-- Table `310Database`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `310Database`.`Users` ;

CREATE TABLE IF NOT EXISTS `310Database`.`Users` (
  `userID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `firstName` VARCHAR(45) NOT NULL COMMENT '',
  `lastName` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `hashedPassword` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`userID`)  COMMENT '',
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `310Database`.`Accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `310Database`.`Accounts` ;

CREATE TABLE IF NOT EXISTS `310Database`.`Accounts` (
  `accountID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `Users_userID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`accountID`, `Users_userID`)  COMMENT '',
  UNIQUE INDEX `accountID_UNIQUE` (`accountID` ASC)  COMMENT '',
  INDEX `fk_Accounts_Users_idx` (`Users_userID` ASC)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  CONSTRAINT `fk_Accounts_Users`
    FOREIGN KEY (`Users_userID`)
    REFERENCES `310Database`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `310Database`.`Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `310Database`.`Transactions` ;

CREATE TABLE IF NOT EXISTS `310Database`.`Transactions` (
  `transactionID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `transactionDate` VARCHAR(45) NOT NULL COMMENT '',
  `amount` FLOAT NOT NULL COMMENT '',
  `category` VARCHAR(45) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `principal` VARCHAR(45) NOT NULL COMMENT '',
  `Accounts_accountID` INT UNSIGNED NOT NULL COMMENT '',
  `Accounts_Users_userID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`transactionID`, `Accounts_accountID`, `Accounts_Users_userID`)  COMMENT '',
  UNIQUE INDEX `transactionID_UNIQUE` (`transactionID` ASC)  COMMENT '',
  INDEX `fk_Transactions_Accounts1_idx` (`Accounts_accountID` ASC, `Accounts_Users_userID` ASC)  COMMENT '',
  CONSTRAINT `fk_Transactions_Accounts1`
    FOREIGN KEY (`Accounts_accountID` , `Accounts_Users_userID`)
    REFERENCES `310Database`.`Accounts` (`accountID` , `Users_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `310Database`.`Budgets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `310Database`.`Budgets` ;

CREATE TABLE IF NOT EXISTS `310Database`.`Budgets` (
  `budgetID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `amount` FLOAT NOT NULL COMMENT '',
  `month` INT NOT NULL COMMENT '',
  `year` INT NOT NULL COMMENT '',
  `category` VARCHAR(45) NOT NULL COMMENT '',
  `Users_userID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`budgetID`, `Users_userID`)  COMMENT '',
  UNIQUE INDEX `budgetID_UNIQUE` (`budgetID` ASC)  COMMENT '',
  INDEX `fk_Budgets_Users1_idx` (`Users_userID` ASC)  COMMENT '',
  CONSTRAINT `fk_Budgets_Users1`
    FOREIGN KEY (`Users_userID`)
    REFERENCES `310Database`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
